### ISSUE TITLE
italian

### ISSUE THREAD

**Issue by Lucky2755** [neebooo/Create-Tram-Additions#2]
hello, italian is supported?

**Comment by Stef-00012** [comment]
bro, #1

**Comment by Lucky2755** [comment]
I don’t see n.1

**Comment by Stef-00012** [comment]
> I don’t see n.1

ho già fatto una pr per aggiungere l'italiano, https://github.com/neebooo/Create-Tram-Additions/pull/1

**Comment by Lucky2755** [comment]
Thank you
